### ISSUE TITLE
Integrate into company?

### ISSUE THREAD

**Issue by seagle0128** [zk-phi/git-complete#26]
`git-complete` uses `popup` which is not stable now. Is it possible to integrate into `company`?

**Comment by zk-phi** [comment]
I've recently migrated from auto-complete to company and started working on this, but in short, it's difficult to convert this to a company backend.

The problem is: company cannot mix different "grab" methods in a single backend. "whole-line" completion takes the current line as "prefix", but "omni" completion does not. So git-complete cannot be implement as a single company backend. I've also tried to implement these two completion methods as separate backends, but it
was not as useful as current implementation (when "whole-line" candidates are
found, "omni" candidates cannot be selected).

I've rewrite the candidate extracting algorithm recently and git-complete is much faster than before. Now a probem is that popup.el does not respond very quickly, so I agree with that, it's good idea to migrate to company if possible.

**Comment by zk-phi** [comment]
> I've also tried to implement these two completion methods as separate backends, but it
was not as useful as current implementation (when "whole-line" candidates are
found, "omni" candidates cannot be selected).

just published the backends: https://github.com/zk-phi/git-complete-company

I've also started working on another omni completion engine called `company-symbol-after-symbol`, which may replace `git-complete-company-omni-backend`.

https://github.com/zk-phi/company-symbol-after-symbol
